version: "3"
services:
  threads:
    image: textile/go-threads:latest
    restart: always
    volumes:
      - "${THRDS_REPO}/threaddb:/data/threaddb"
    environment:
      - THRDS_REPO
      - THRDS_HOSTADDR
      - THRDS_APIADDR=/ip4/0.0.0.0/tcp/6006
      - THRDS_APIPROXYADDR=/ip4/0.0.0.0/tcp/6007
      - THRDS_CONNLOWWATER
      - THRDS_CONNHIGHWATER
      - THRDS_CONNGRACEPERIOD
      - THRDS_KEEPALIVEINTERVAL
      - THRDS_ENABLENETPUBSUB
      - THRDS_MONGOURI=mongodb://mongo:27017
      - THRDS_MONGODATABASE=threaddb
      - THRDS_DEBUG
    ports:
      - "4006:4006"
      - "127.0.0.1:6006:6006"
      - "127.0.0.1:6007:6007"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - "${THRDS_REPO}/mongodb:/data/mongodb"
    ports:
      - "127.0.0.1:27017:27017"
    command:
      - /bin/bash
      - -c
      - |
        /usr/bin/mongod --fork --logpath /var/log/mongod.log --bind_ip_all --replSet rs0
        mongo --eval 'rs.initiate({_id: "rs0", version: 1, members: [{ _id: 0, host: "mongo:27017" }]})'
        tail -f /var/log/mongod.log
