name: threads_client_grpc
version: 0.0.0
description: A gRPC client for interacting with a remote ThreadDB service.
homepage: 'https://github.com/textileio/go-threads'
repository: 'https://github.com/textileio/go-threads'
environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
  async: ^2.2.0
  grpc: ^2.1.3
  protobuf: ^1.0.1
dev_dependencies:
  pubspec_version: ^0.6.1

