[global]
plan    = "go-threads"
case    = "sync-threads"
builder = "docker:go"
runner  = "local:docker"
total_instances = 5
  [global.build]
  dependencies = [
      { module = "github.com/textileio/go-threads", version = "4c90b2d32403eac31871637dc0922ef5ee6371a9"},
  ]

[[groups]]
id = "always-on"
instances = { count = 3 }

[[groups]]
id = "early-stopper"
instances = { count = 1 }
  [groups.run]
  test_params = {early-stop="true"}

[[groups]]
id = "later-joiner"
instances = { count = 1 }
  [groups.run]
  test_params = {late-start="true"}
